name: bb
description: A new Flutter project

publish_to: 'none' # Remove this line if you want to publish to the App Store

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5

  # ✅ State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  # ✅ HTTP client
  dio: ^5.4.1

  # ✅ Local storage
  shared_preferences: ^2.2.2

  # ✅ Localization
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.3

  # ✅ Animations
  animated_splash_screen: ^1.3.0
  flutter_animate: ^4.5.0

  # ✅ Routing
  go_router: ^15.1.2

  # ✅ Screen Util
  flutter_screenutil: ^5.9.3

  # ✅ Meta package
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/translations/
